-- AlterTable
ALTER TABLE "salary" ALTER COLUMN "salary_gross" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "salary_netto" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "pension_insurance" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "disability_insurance" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "sickness_insurance" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "social_insurance_total" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "income_tax" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "health_insurance" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "final_tax_base" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "user" ALTER COLUMN "night_time_rate_of_pay" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "rate_of_pay" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "revenue_expenditure" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "tax_benefit" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "total_salary" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "total_tax" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "disability_insurance_percent" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "four_brigade_percent" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "health_insurance_percent" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "income_tax_percent" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "minimum_rate" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "pension_insurance_percent" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "sickness_insurance_percent" SET DATA TYPE DOUBLE PRECISION;
