-- AlterTable
ALTER TABLE "goals" ALTER COLUMN "percent_compiled" SET DEFAULT 0,
ALTER COLUMN "link" DROP DEFAULT,
ALTER COLUMN "link" SET DATA TYPE TEXT,
ALTER COLUMN "title" DROP DEFAULT,
ALTER COLUMN "title" SET DATA TYPE TEXT;
